version: "3.8"
services:
  ai-twitch-tts:
    image: johnnycyan/ai-twitch-tts:main
    container_name: tts
    ports:
      - 8034:8080
    environment:
      - ELEVENLABS_KEY=${ELEVENLABS_KEY}
      - ELEVENLABS_PRICE=${ELEVENLABS_PRICE}
      - SERVER_URL=${SERVER_URL}
      - SENTRY_URL=${SENTRY_URL}
      - TTS_KEY=${TTS_KEY}
      - PALLY_KEYS=${PALLY_KEYS}
      - VOICES=${VOICES}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - FFMPEG_ENABLED=true
    volumes:
      - ./effects:/app/effects
      - ./alerts:/app/alerts
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

